# Generated by Django 5.2.17 on 2026-09-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nama pakaian")),
                ("description", models.TextField(verbose_name="deskripsi")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("top", "Atasan"),
                            ("bottom", "Bawahan"),
                            ("dress", "Dress"),
                            ("outerwear", "Outerwear"),
                            ("footwear", "Alas kaki"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="kategori",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("other", "Lainnya"),
                        ],
                        max_length=10,
                        verbose_name="ukuran",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "Baru"),
                            ("like_new", "Seperti baru"),
                            ("good", "Baik"),
                            ("fair", "Cukup baik"),
                        ],
                        max_length=20,
                        verbose_name="kondisi",
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Tersedia"),
                            ("unavailable", "Tidak tersedia"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status ketersediaan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothing_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pemilik",
                    ),
                ),
            ],
            options={
                "verbose_name": "pakaian",
                "verbose_name_plural": "pakaian",
                "ordering": ["-created_at"],
            },
        ),
    ]
