# Generated by Django 5.2.17 on 2026-10-01 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clothing_catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="pesan")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu"),
                            ("accepted", "Diterima"),
                            ("rejected", "Ditolak"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offered_clothing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offered_swap_requests",
                        to="clothing_catalog.clothing",
                        verbose_name="pakaian yang ditawarkan",
                    ),
                ),
                (
                    "requested_clothing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_swap_requests",
                        to="clothing_catalog.clothing",
                        verbose_name="pakaian yang diminta",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_swap_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="pengaju",
                    ),
                ),
            ],
            options={
                "verbose_name": "swap request",
                "verbose_name_plural": "swap request",
                "ordering": ["-created_at"],
            },
        ),
    ]
