# Generated by Django 5.2.17 on 2026-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("Meetup", "Meetup"), ("Delivery", "Delivery")],
                        default="Meetup",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("InProgress", "In Progress"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("Disputed", "Disputed"),
                        ],
                        default="Waiting",
                        max_length=20,
                    ),
                ),
                (
                    "requester_resi",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("owner_resi", models.CharField(blank=True, max_length=100, null=True)),
                ("requester_resi_valid", models.BooleanField(default=False)),
                ("owner_resi_valid", models.BooleanField(default=False)),
                (
                    "requester_delivery_estimate",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "owner_delivery_estimate",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("requester_received", models.BooleanField(default=False)),
                ("owner_received", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
