# Generated by Django 5.2.17 on 2026-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="meetup_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="meetup_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
