# Generated by Django 5.2.17 on 2026-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transaction", "0003_transaction_initiator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="initiator",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="is_reported",
        ),
        migrations.AddField(
            model_name="transaction",
            name="owner_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="requester_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
